import posixpath
from datetime import datetime, timezone
from pathlib import Path

import yaml

from ..provision.ansible_writer import ROLE_META_TEMPLATE
from ..validate.test_deploy import DerivedCheck
from .storyline import Artefact, Storyline

ARTEFACT_ROLE_NAME = "forensic_artefacts"

COMBINED_PLAYBOOK_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
- hosts: all
  become: true
  roles:
    - {scenario_role}
    - {artefact_role}
"""


def _build_task_and_check(artefact: Artefact) -> tuple[list[dict], list[DerivedCheck]]:
    """Build the Ansible task(s) that plant one artefact, and the matching
    verification check(s) - built together so task names can never drift
    out of sync between planting and verification, the same reasoning
    behind provision/ansible_writer.py's ROLE_NAMESPACE constant.
    """
    if artefact.kind in ("log_entry", "shell_history"):
        task_name = artefact.description
        # Real log files are typically 0644 (root-owned, world-readable);
        # real shell history files are typically 0600 (private to the
        # user) - matching that isn't just tidiness, it's part of what
        # makes the planted artefact look like it was actually produced
        # by normal system/shell behaviour rather than dropped in by a
        # provisioning tool.
        mode = "0600" if artefact.kind == "shell_history" else "0644"
        tasks = [{
            "name": task_name,
            "ansible.builtin.lineinfile": {
                "path": artefact.target_path,
                "line": artefact.content,
                "insertafter": "EOF",
                "create": True,
                "mode": mode,
            },
        }]
        checks = [_grep_check(task_name, artefact.target_path, artefact.content)]
        return tasks, checks

    if artefact.kind == "email_draft":
        task_name = artefact.description
        directory = posixpath.dirname(artefact.target_path)
        tasks = [
            {
                "name": f"{task_name} (create directory)",
                "ansible.builtin.file": {"path": directory, "state": "directory", "mode": "0700"},
            },
            {
                "name": task_name,
                "ansible.builtin.copy": {"dest": artefact.target_path, "content": artefact.content, "mode": "0600"},
            },
        ]
        # A multi-line body isn't a single grep -F target; the Subject
        # header is always a single distinctive line, so verify against
        # that instead of the full content.
        subject_line = next((line for line in artefact.content.splitlines() if line.startswith("Subject: ")), "")
        checks = [_grep_check(task_name, artefact.target_path, subject_line)]
        return tasks, checks

    if artefact.kind == "deleted_file":
        write_name = f"{artefact.description} (write)"
        delete_name = f"{artefact.description} (delete)"
        tasks = [
            {"name": write_name, "ansible.builtin.copy": {"dest": artefact.target_path, "content": artefact.content, "mode": "0600"}},
            {"name": delete_name, "ansible.builtin.file": {"path": artefact.target_path, "state": "absent"}},
        ]
        absent_check = DerivedCheck(
            command=f"bash -c \"sudo test -e {artefact.target_path} && echo STILL_EXISTS || echo CONFIRMED_ABSENT\"",
            expected="CONFIRMED_ABSENT",
            task_name=delete_name,
        )
        return tasks, [absent_check]

    if artefact.kind == "backdated_file":
        if not artefact.timestamp:
            raise ValueError(f"backdated_file artefact {artefact.description!r} needs a timestamp")
        write_name = f"{artefact.description} (write)"
        touch_name = f"{artefact.description} (backdate)"
        # artefact.timestamp is naive (no tzinfo) and treated as UTC on
        # both sides explicitly - the guest and this host may be in
        # different local timezones, and datetime.fromisoformat(...).timestamp()
        # on a naive value interprets it as *this host's* local time,
        # which would silently mismatch whatever local time the guest's
        # `touch -d` used if either side were left to its own default.
        # The trailing "Z" forces GNU touch to interpret the string as
        # UTC; utc_dt below matches that on the Python side.
        utc_dt = datetime.fromisoformat(artefact.timestamp).replace(tzinfo=timezone.utc)
        tasks = [
            {"name": write_name, "ansible.builtin.copy": {"dest": artefact.target_path, "content": artefact.content, "mode": "0644"}},
            {
                "name": touch_name,
                "ansible.builtin.command": f"touch -d '{artefact.timestamp}Z' {artefact.target_path}",
                # touch's exit code alone doesn't tell Ansible whether the
                # mtime actually changed, so Ansible can't compute
                # changed/ok for this task on its own - it would always
                # report changed regardless, which ansible-lint's
                # no-changed-when rule correctly flags as unreliable.
                # changed_when: true makes that explicit rather than
                # accidental: the verification check below confirms the
                # actual on-disk timestamp regardless (that's the part
                # that matters for the evidence itself), so attribution
                # for *this specific* task is consequently always
                # "changed" by design - a known, documented limitation
                # rather than something worth a bigger fix. See
                # docs/METHODOLOGY.md (week 5).
                "changed_when": True,
            },
        ]
        stat_check = DerivedCheck(
            command=f"sudo stat -c %Y {artefact.target_path}",
            expected=str(int(utc_dt.timestamp())),
            task_name=touch_name,
        )
        return tasks, [stat_check]

    raise ValueError(f"unknown artefact kind: {artefact.kind!r}")


def _grep_check(task_name: str, path: str, content: str) -> DerivedCheck:
    escaped = content.replace("'", "'\\''")
    return DerivedCheck(
        command=f"sudo grep -F -- '{escaped}' {path}",
        expected=content,
        task_name=task_name,
    )


def write_artefact_role(storyline: Storyline, run_dir: Path, scenario_role_name: str = "training_vm") -> Path:
    """Write an Ansible role that plants `storyline`'s artefacts, and
    extend playbook.yml to run it alongside the scenario role.

    playbook.yml is rewritten wholesale (COMBINED_PLAYBOOK_TEMPLATE)
    rather than parsed and patched: it's a fixed two-role structure, and
    round-tripping through YAML parse/re-serialize for something this
    simple would risk reformatting the file for no benefit.
    """
    role_dir = run_dir / "roles" / ARTEFACT_ROLE_NAME
    (role_dir / "tasks").mkdir(parents=True, exist_ok=True)
    (role_dir / "meta").mkdir(parents=True, exist_ok=True)

    all_tasks: list[dict] = []
    for artefact in storyline.artefacts:
        tasks, _ = _build_task_and_check(artefact)
        all_tasks.extend(tasks)

    (role_dir / "tasks" / "main.yml").write_text(
        yaml.dump(all_tasks, sort_keys=False, default_flow_style=False), encoding="utf-8"
    )
    (role_dir / "meta" / "main.yml").write_text(ROLE_META_TEMPLATE, encoding="utf-8")

    (run_dir / "playbook.yml").write_text(
        COMBINED_PLAYBOOK_TEMPLATE.format(scenario_role=scenario_role_name, artefact_role=ARTEFACT_ROLE_NAME),
        encoding="utf-8",
    )

    return role_dir


def derive_checks_from_storyline(storyline: Storyline) -> list[DerivedCheck]:
    """Build the verification checks for every artefact in `storyline`.

    Feeds directly into test_deploy.test_deploy() alongside (or instead
    of) the scenario role's own derive_checks_from_role() output - both
    return the same DerivedCheck type, so test_deploy()'s existing
    boot/verify/destroy/attribution machinery needs no changes at all to
    verify planted evidence. category="artefact" is set here (the single
    place every check passes through on its way out) rather than at each
    individual construction site, so it can't be forgotten on a future
    artefact kind.
    """
    checks: list[DerivedCheck] = []
    for artefact in storyline.artefacts:
        _, artefact_checks = _build_task_and_check(artefact)
        checks.extend(artefact_checks)
    for check in checks:
        check.category = "artefact"
    return checks
