import re
import textwrap
from pathlib import Path

import yaml

from .repair import (
    repair_lineinfile_backreferences,
    repair_user_module_path_misuse,
    repair_yaml_text,
)

YAML_BLOCK_PATTERN = re.compile(r"```ya?ml\s*\n(.*?)```", re.DOTALL)

# Must match the `author:` field below - ansible-compat's local role
# installer (which Molecule calls during "prerun") namespaces the role
# under this value, symlinking it as e.g. "forensicforge.training_vm"
# rather than bare "training_vm" - confirmed by inspecting the resulting
# symlink under ~/.ansible/roles/ (see docs/METHODOLOGY.md, week 4).
# molecule_writer.py's converge.yml needs the same prefix or Ansible's
# role search won't find it.
ROLE_NAMESPACE = "forensicforge"

ROLE_META_TEMPLATE = f"""\
galaxy_info:
  author: {ROLE_NAMESPACE}
  description: Auto-generated training scenario role - do not edit by hand.
  license: MIT
  min_ansible_version: "2.14"

dependencies: []
"""

PLAYBOOK_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
- hosts: all
  become: true
  roles:
    - {role_name}
"""


class AnsibleParseError(Exception):
    """Raised when LLM output can't be turned into a valid Ansible role.

    Carries the raw LLM output so the caller can show it to the user
    instead of silently writing broken YAML to disk. Real policy gating
    (ansible-lint, Checkov) is week 4's job - this is just "is it even
    parseable," which is the minimum bar for not writing garbage.
    """

    def __init__(self, message: str, raw_output: str):
        super().__init__(message)
        self.raw_output = raw_output


def extract_yaml_block(raw_output: str) -> str:
    match = YAML_BLOCK_PATTERN.search(raw_output)
    if not match:
        raise AnsibleParseError(
            "No ```yaml code block found in the LLM output.", raw_output
        )
    # textwrap.dedent(), not a bare .strip(): when the LLM wraps the whole
    # fenced block inside a numbered markdown list item (e.g. "1. ```yaml"),
    # every line in the block carries the same leading indentation from
    # that list nesting. .strip() only trims the very start/end of the
    # *whole string* - it removes the first line's leading whitespace but
    # leaves every other line's indentation untouched, desyncing the first
    # task's "- name:" from its own sibling keys ("ansible.builtin.X:")
    # one indent level deeper than it should be relative to "name:".
    # Confirmed as the actual root cause of a real "mapping values are not
    # allowed here" failure this week, on output that read as perfectly
    # valid YAML by eye - the bug was invisible until the exact extracted
    # string (not the raw LLM output) was inspected directly. dedent()
    # removes the common leading whitespace from every line uniformly,
    # so relative indentation survives regardless of how deep the fence
    # itself was nested. See docs/METHODOLOGY.md (week 6).
    return textwrap.dedent(match.group(1)).strip()


def parse_tasks(yaml_text: str, raw_output: str) -> tuple[list[dict], list[str]]:
    """Parse `yaml_text` into a task list, applying repair.py's known-shape
    fixes where they apply. Returns (tasks, repair_notes) - notes is empty
    when nothing needed fixing. Still raises AnsibleParseError, unchanged,
    for anything the repairs don't recognize.
    """
    repair_notes: list[str] = []
    try:
        tasks = yaml.safe_load(yaml_text)
    except yaml.YAMLError as exc:
        repaired_text, note = repair_yaml_text(yaml_text, exc)
        if repaired_text is None:
            raise AnsibleParseError(f"Extracted YAML failed to parse: {exc}", raw_output) from exc
        try:
            tasks = yaml.safe_load(repaired_text)
        except yaml.YAMLError as retry_exc:
            raise AnsibleParseError(
                f"Extracted YAML failed to parse, and an automatic repair attempt "
                f"({note}) still didn't produce valid YAML: {retry_exc}", raw_output,
            ) from retry_exc
        yaml_text = repaired_text
        repair_notes.append(note)

    if not isinstance(tasks, list) or not tasks:
        raise AnsibleParseError("Extracted YAML is not a non-empty list of tasks.", raw_output)

    for i, task in enumerate(tasks):
        if not isinstance(task, dict) or "name" not in task:
            raise AnsibleParseError(
                f"Task {i} is not a mapping with a 'name' key: {task!r}", raw_output
            )

    tasks, backref_notes = repair_lineinfile_backreferences(tasks)
    repair_notes.extend(backref_notes)
    tasks, user_path_notes = repair_user_module_path_misuse(tasks)
    repair_notes.extend(user_path_notes)

    return tasks, repair_notes


def write_ansible_role(raw_output: str, run_dir: Path, role_name: str = "training_vm") -> tuple[Path, list[str]]:
    """Extract, validate, and write RAG output as an Ansible role + playbook.

    Nothing is written to disk if extraction or parsing fails - raises
    AnsibleParseError instead, with the raw LLM output attached. Returns
    (role_dir, repair_notes): repair_notes lists any known-shape fixes
    repair.py applied to the LLM's output before writing it - never
    applied silently, always surfaced to the caller (see provision_spec()
    and the `provision` CLI command). The written tasks/main.yml reflects
    the *repaired* tasks, not the LLM's original, exact text - the
    original is still recoverable from generation.md.
    """
    yaml_text = extract_yaml_block(raw_output)
    tasks, repair_notes = parse_tasks(yaml_text, raw_output)

    role_dir = run_dir / "roles" / role_name
    (role_dir / "tasks").mkdir(parents=True, exist_ok=True)
    (role_dir / "meta").mkdir(parents=True, exist_ok=True)

    (role_dir / "tasks" / "main.yml").write_text(
        yaml.dump(tasks, sort_keys=False, default_flow_style=False), encoding="utf-8"
    )
    (role_dir / "meta" / "main.yml").write_text(ROLE_META_TEMPLATE, encoding="utf-8")
    (run_dir / "playbook.yml").write_text(
        PLAYBOOK_TEMPLATE.format(role_name=role_name), encoding="utf-8"
    )

    return role_dir, repair_notes
