import re
from pathlib import Path

import yaml

YAML_BLOCK_PATTERN = re.compile(r"```ya?ml\s*\n(.*?)```", re.DOTALL)

# Must match the `author:` field below - ansible-compat's local role
# installer (which Molecule calls during "prerun") namespaces the role
# under this value, symlinking it as e.g. "forensicforge.training_vm"
# rather than bare "training_vm" - confirmed by inspecting the resulting
# symlink under ~/.ansible/roles/ (see docs/METHODOLOGY.md, week 4).
# molecule_writer.py's converge.yml needs the same prefix or Ansible's
# role search won't find it.
ROLE_NAMESPACE = "forensicforge"

ROLE_META_TEMPLATE = f"""\
galaxy_info:
  author: {ROLE_NAMESPACE}
  description: Auto-generated training scenario role - do not edit by hand.
  license: MIT
  min_ansible_version: "2.14"

dependencies: []
"""

PLAYBOOK_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
- hosts: all
  become: true
  roles:
    - {role_name}
"""


class AnsibleParseError(Exception):
    """Raised when LLM output can't be turned into a valid Ansible role.

    Carries the raw LLM output so the caller can show it to the user
    instead of silently writing broken YAML to disk. Real policy gating
    (ansible-lint, Checkov) is week 4's job - this is just "is it even
    parseable," which is the minimum bar for not writing garbage.
    """

    def __init__(self, message: str, raw_output: str):
        super().__init__(message)
        self.raw_output = raw_output


def extract_yaml_block(raw_output: str) -> str:
    match = YAML_BLOCK_PATTERN.search(raw_output)
    if not match:
        raise AnsibleParseError(
            "No ```yaml code block found in the LLM output.", raw_output
        )
    return match.group(1).strip()


def parse_tasks(yaml_text: str, raw_output: str) -> list[dict]:
    try:
        tasks = yaml.safe_load(yaml_text)
    except yaml.YAMLError as exc:
        raise AnsibleParseError(f"Extracted YAML failed to parse: {exc}", raw_output) from exc

    if not isinstance(tasks, list) or not tasks:
        raise AnsibleParseError("Extracted YAML is not a non-empty list of tasks.", raw_output)

    for i, task in enumerate(tasks):
        if not isinstance(task, dict) or "name" not in task:
            raise AnsibleParseError(
                f"Task {i} is not a mapping with a 'name' key: {task!r}", raw_output
            )
    return tasks


def write_ansible_role(raw_output: str, run_dir: Path, role_name: str = "training_vm") -> Path:
    """Extract, validate, and write RAG output as an Ansible role + playbook.

    Nothing is written to disk if extraction or parsing fails - raises
    AnsibleParseError instead, with the raw LLM output attached.
    """
    yaml_text = extract_yaml_block(raw_output)
    parse_tasks(yaml_text, raw_output)  # validates; raises on failure, writes nothing

    role_dir = run_dir / "roles" / role_name
    (role_dir / "tasks").mkdir(parents=True, exist_ok=True)
    (role_dir / "meta").mkdir(parents=True, exist_ok=True)

    (role_dir / "tasks" / "main.yml").write_text(yaml_text + "\n", encoding="utf-8")
    (role_dir / "meta" / "main.yml").write_text(ROLE_META_TEMPLATE, encoding="utf-8")
    (run_dir / "playbook.yml").write_text(
        PLAYBOOK_TEMPLATE.format(role_name=role_name), encoding="utf-8"
    )

    return role_dir
