from pathlib import Path

from .. import config
from .ansible_writer import ROLE_NAMESPACE

MOLECULE_YML_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
driver:
  name: vagrant
  # Provider goes here (driver.provider.name), not under platforms[] -
  # confirmed by reproducing the failure this got wrong the first time:
  # putting it under platforms[].provider silently fell back to
  # molecule-plugins' vagrant module default of "virtualbox", which then
  # hit the same VirtualBox/Memory Integrity conflict week 3 already
  # worked around by switching to Hyper-V. See docs/METHODOLOGY.md (week 4).
  provider:
    name: {provider}
platforms:
  - name: instance
    box: {box}
provisioner:
  name: ansible
verifier:
  name: ansible
"""

CONVERGE_YML_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
- name: Converge
  hosts: all
  become: true
  roles:
    - {role_namespace}.{role_name}
"""


def write_molecule_scenario(
    role_dir: Path,
    role_name: str,
    box: str = config.VAGRANT_BOX,
    provider: str = config.VAGRANT_PROVIDER,
) -> Path:
    """Write a Molecule "default" scenario for the generated role.

    Roles are generated per-run rather than hand-written, so this is a
    template rendered fresh for each one (role name substituted in) -
    see docs/METHODOLOGY.md (week 4) for why a Vagrant-driven scenario
    rather than Molecule's default Docker driver.

    converge.yml references the role as "{ROLE_NAMESPACE}.{role_name}",
    not bare role_name: Molecule's prerun step symlinks the role under
    that namespaced name (from meta/main.yml's `author:` field, written
    by ansible_writer.py), and Ansible's role search won't find it under
    the bare name - confirmed by reproducing the resulting "role not
    found" error. See ROLE_NAMESPACE's docstring in ansible_writer.py.
    """
    scenario_dir = role_dir / "molecule" / "default"
    scenario_dir.mkdir(parents=True, exist_ok=True)

    (scenario_dir / "molecule.yml").write_text(
        MOLECULE_YML_TEMPLATE.format(box=box, provider=provider), encoding="utf-8"
    )
    (scenario_dir / "converge.yml").write_text(
        CONVERGE_YML_TEMPLATE.format(role_namespace=ROLE_NAMESPACE, role_name=role_name),
        encoding="utf-8",
    )
    return scenario_dir
