from pathlib import Path

from .. import config

PROVISIONING_PATH = "/home/vagrant/forensicforge"

VAGRANTFILE_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
# Regenerate by re-running the provision command.

Vagrant.configure("2") do |config|
  config.vm.box = "{box}"
  config.vm.hostname = "{hostname}"

  # Without this, `vagrant up` on Hyper-V prompts interactively whenever
  # more than one virtual switch exists on the host - which test-deploy
  # can never answer (no stdin fed to it), so it hangs forever instead of
  # failing (confirmed by reproducing the hang directly). There is no
  # Hyper-V *provider* setting for this (checked against Vagrant's own
  # config.rb - no such attribute exists, despite several guides online
  # implying otherwise); the provider's configure.rb action instead looks
  # for a `bridge:` on a public_network/private_network entry and skips
  # the prompt if one matches an available switch by name. "public_network"
  # gives the VM an IP on the same network as the switch (Hyper-V has no
  # VirtualBox-style default NAT), which is what this project's VMs need
  # regardless of the prompt issue.
  config.vm.network "public_network", bridge: "{hyperv_switch}"

  # A deterministic Hyper-V VM name (not Vagrant's own auto-generated
  # "<dir>_default_<random>" one), so build-scenario's image-export step
  # (week 6) can find this specific VM by name afterward without needing
  # to parse Vagrant's internal .vagrant/ state files. `vmname` is a real
  # Hyper-V-provider config attribute - confirmed against Vagrant's own
  # plugins/providers/hyperv/config.rb source before relying on it, after
  # getting burned once already this project assuming a provider option
  # existed (`vmswitch` - see the switch-selection section above).
  config.vm.provider "hyperv" do |h|
    h.vmname = "{hostname}"
  end

  # Copied over SSH rather than relying on a synced folder: VirtualBox needs
  # Guest Additions for its default /vagrant sync, and Hyper-V's equivalent
  # needs an SMB share (host account credentials, set up interactively).
  # A plain file provisioner works identically on every provider with the
  # SSH access Vagrant already has, and needs no credentials at all.
  #
  # The destination directory is created explicitly first: Vagrant's file
  # provisioner does not reliably create missing parent directories on its
  # own. Only playbook.yml and roles/ are copied (not the whole run
  # directory via "."), since that would also pull in .vagrant/ - which
  # contains files the running `vagrant` process itself holds open, and
  # broke the transfer.
  #
  # privileged: false is required, not optional: Vagrant's shell
  # provisioner defaults to privileged: true (root), so without this the
  # directory ends up root:root, and the *next* provisioner's SCP upload
  # (which connects as the plain "vagrant" user, not root) fails with a
  # permissions error trying to write into it. This went unnoticed until
  # week 5 forced every test-deploy to actually reprovision from scratch
  # (`provision=True`, closing the attribution gap) - Vagrant's own
  # default of skipping already-provisioned machines had been quietly
  # masking it on every machine reused from an earlier manual boot.
  #
  # roles/ is removed before copying, not just re-copied over: a real
  # rerun on a genuinely fresh VM (confirmed via "Importing a Hyper-V
  # instance" in the log, not a resumed one) still applied an *older*
  # version of a role than what was on disk at the time - no confirmed
  # root cause, but Vagrant's directory-copy file provisioner is the only
  # thing between "what's on disk here" and "what the guest sees", so
  # forcing a clean destination removes whatever staleness mechanism was
  # responsible rather than requiring one to be pinned down first.
  # Ansible is installed here, explicitly, in this project's own shell
  # provisioner - not left to ansible_local's own install logic below.
  # Four different attempts at letting Vagrant/apt handle this failed
  # live, each a different way: the default install_mode's PPA add
  # (`add-apt-repository ppa:ansible/ansible`) failed with a Launchpad
  # team-resolution error, independently, on two separate runs; switching
  # to install_mode "pip" then failed because its default bootstrap
  # (get-pip.py) has dropped support for anything older than Python 3.10
  # (this box ships 3.8); a version-pinned get-pip.py URL fixed *that*,
  # but Vagrant's own subsequent `pip install --upgrade ansible` step
  # (hardcoded, not something this project's Vagrantfile controls) then
  # failed with "pip: command not found"; installing the plain `ansible`
  # apt package directly (confirmed published in focal's universe
  # component via Launchpad's package API) sidestepped all of that, but
  # is version 2.9.6 (from 2020) - which predates Ansible's collections
  # system entirely, so it can't resolve `community.general.ufw` (or any
  # other collection-qualified module name) at all. Every generated role
  # that uses `ufw` - most of them, via the knowledge corpus's own
  # ansible_tasks/manage_ufw_firewall_rule.md - would fail the same way.
  # Fixed by installing a modern Ansible via pip3 instead of apt's
  # ancient package: `python3-pip` (the apt package, not get-pip.py -
  # sidesteps that whole Python-version problem, since it's prebuilt for
  # this exact box's Python) gets a working pip3, then `pip3 install
  # ansible` - deliberately the full `ansible` PyPI package, not the
  # minimal `ansible-core` - since the full package bundles a curated set
  # of collections (community.general included) that ansible-core alone
  # does not, which is exactly what this project's generated roles need.
  # See docs/METHODOLOGY.md (week 6) for the full chain of attempts.
  #
  # python3-pymysql and python3-psycopg2 (confirmed published in focal's
  # archive via Launchpad's package API, not assumed) are installed
  # unconditionally alongside Ansible itself, not only when a generated
  # role happens to need one: Ansible's `mysql_user`/`postgresql_user`
  # modules (and similar) need a Python DB driver present on the *guest*
  # to connect at all - confirmed live, a database-misconfiguration spec
  # failed with "A MySQL module is required" on a `mysql_user` task with
  # nothing on the guest to satisfy it. Deterministic given the module
  # choice (not stochastic like the earlier bugs above), and this
  # project's knowledge corpus/generated roles will keep hitting it for
  # any future database spec, MySQL or Postgres - cheap (a few MB) to
  # install preemptively versus detecting per-role which driver a
  # specific run's tasks would need.
  config.vm.provision "shell", inline: "mkdir -p {provisioning_path} && rm -rf {provisioning_path}/roles && sudo apt-get update -qq && sudo apt-get install -y -qq python3-pip python3-pymysql python3-psycopg2 && sudo pip3 install --quiet ansible", privileged: false
  config.vm.provision "file", source: "playbook.yml", destination: "{provisioning_path}/playbook.yml"
  config.vm.provision "file", source: "roles", destination: "{provisioning_path}/roles"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.provisioning_path = "{provisioning_path}"
    ansible.install = false
  end
end
"""


def write_vagrantfile(
    run_dir: Path,
    hostname: str,
    box: str = config.VAGRANT_BOX,
    hyperv_switch: str = config.VAGRANT_HYPERV_SWITCH,
) -> Path:
    """Write a per-run Vagrantfile pointing at `box` with the ansible_local provisioner.

    ansible_local (not the host-side "ansible" provisioner) installs and
    runs Ansible inside the guest - see docs/METHODOLOGY.md for why, but
    in short: Ansible doesn't run natively on Windows, so this avoids
    requiring a host-side Ansible install.

    No explicit roles_path is set: ansible_local doesn't support that
    option at all (confirmed against Vagrant's docs after a real `vagrant
    up` rejected it - "roles_path" isn't in ansible_local's own options or
    the options shared between it and the host-side "ansible" provisioner).
    Role discovery instead relies on Ansible's default search for a
    `roles/` directory next to the playbook, which is exactly
    ansible_writer.py's output layout (playbook.yml and roles/ as siblings
    under run_dir) - now copied to PROVISIONING_PATH on the guest via the
    "file" provisioners above, so that layout is preserved there too.
    """
    content = VAGRANTFILE_TEMPLATE.format(
        box=box, hostname=hostname, provisioning_path=PROVISIONING_PATH, hyperv_switch=hyperv_switch
    )
    path = run_dir / "Vagrantfile"
    path.write_text(content, encoding="utf-8")
    return path
