from pathlib import Path

from .. import config

PROVISIONING_PATH = "/home/vagrant/forensicforge"

VAGRANTFILE_TEMPLATE = """\
# Auto-generated by `forensicforge provision` - do not edit by hand.
# Regenerate by re-running the provision command.

Vagrant.configure("2") do |config|
  config.vm.box = "{box}"
  config.vm.hostname = "{hostname}"

  # Copied over SSH rather than relying on a synced folder: VirtualBox needs
  # Guest Additions for its default /vagrant sync, and Hyper-V's equivalent
  # needs an SMB share (host account credentials, set up interactively).
  # A plain file provisioner works identically on every provider with the
  # SSH access Vagrant already has, and needs no credentials at all.
  #
  # The destination directory is created explicitly first: Vagrant's file
  # provisioner does not reliably create missing parent directories on its
  # own. Only playbook.yml and roles/ are copied (not the whole run
  # directory via "."), since that would also pull in .vagrant/ - which
  # contains files the running `vagrant` process itself holds open, and
  # broke the transfer.
  config.vm.provision "shell", inline: "mkdir -p {provisioning_path}"
  config.vm.provision "file", source: "playbook.yml", destination: "{provisioning_path}/playbook.yml"
  config.vm.provision "file", source: "roles", destination: "{provisioning_path}/roles"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.provisioning_path = "{provisioning_path}"
  end
end
"""


def write_vagrantfile(run_dir: Path, hostname: str, box: str = config.VAGRANT_BOX) -> Path:
    """Write a per-run Vagrantfile pointing at `box` with the ansible_local provisioner.

    ansible_local (not the host-side "ansible" provisioner) installs and
    runs Ansible inside the guest - see docs/METHODOLOGY.md for why, but
    in short: Ansible doesn't run natively on Windows, so this avoids
    requiring a host-side Ansible install.

    No explicit roles_path is set: ansible_local doesn't support that
    option at all (confirmed against Vagrant's docs after a real `vagrant
    up` rejected it - "roles_path" isn't in ansible_local's own options or
    the options shared between it and the host-side "ansible" provisioner).
    Role discovery instead relies on Ansible's default search for a
    `roles/` directory next to the playbook, which is exactly
    ansible_writer.py's output layout (playbook.yml and roles/ as siblings
    under run_dir) - now copied to PROVISIONING_PATH on the guest via the
    "file" provisioners above, so that layout is preserved there too.
    """
    content = VAGRANTFILE_TEMPLATE.format(
        box=box, hostname=hostname, provisioning_path=PROVISIONING_PATH
    )
    path = run_dir / "Vagrantfile"
    path.write_text(content, encoding="utf-8")
    return path
